ProjectWebApp/ProjectWebApp/Controllers/ServiceRequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HSMSBusinessObjects;
using Microsoft.AspNetCore.Authorization;
using ProjectWebApp.ViewModel;

namespace ProjectWebApp.Controllers
{
    public class ServiceRequestsController : Controller
    {
        private readonly HSMSContext _context;

        public ServiceRequestsController()
        {
            _context = new HSMSContext();
        }

        // GET: ServiceRequests
        public async Task<IActionResult> Index(string SearchString)
        {
            IEnumerable<ServiceRequest> serviceRequestList;

            serviceRequestList = _context.ServiceRequests.Include(s => s.Comment).Include(s => s.IdNavigation).Include(s => s.Technician);

            if (!string.IsNullOrEmpty(SearchString))
            {
                serviceRequestList = serviceRequestList.Where(x => x.Description.Contains(SearchString));
            }

            var serviceRequestVM = new NewServiceRequestViewModel
            {
                ServiceRequests = serviceRequestList
            };

            return View(serviceRequestVM);
        }

        // GET: ServiceRequests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ServiceRequests == null)
            {
                return NotFound();
            }

            var serviceRequest = await _context.ServiceRequests
                .Include(s => s.Comment)
                .Include(s => s.IdNavigation)
                .Include(s => s.Technician)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (serviceRequest == null)
            {
                return NotFound();
            }

            return View(serviceRequest);
        }

        // GET: ServiceRequests/Create
        public IActionResult Create()
        {
            ViewData["CommentId"] = new SelectList(_context.Comments, "CommentId", "Notes");
            ViewData["Id"] = new SelectList(_context.Services, "ServiceId", "ServiceName");
            ViewData["TechnicianId"] = new SelectList(_context.AppUsers, "Id", "Id");
            return View();
        }

        // POST: ServiceRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,DateNeeded,Price,CommentId,TechnicianId,IsPending")] ServiceRequest serviceRequest)
        {
            if (ModelState.IsValid)
            {
                _context.ChangeTracker.DetectChanges();
                _context.Add(serviceRequest);

                var entry = _context.ChangeTracker.Entries().FirstOrDefault();

                Log log = new Log
                {
                    Table = entry.Entity.GetType().Name,
                    Status = entry.State.ToString(),
                    LDate = DateTime.Now,
                    UserId = _context.AppUsers.Where(x => x.UserName == User.Identity.Name).FirstOrDefault().Id,
                    User = _context.AppUsers.Where(x => x.Id == _context.AppUsers.Where(x => x.UserName == User.Identity.Name).FirstOrDefault().Id).FirstOrDefault(),
                    OriginalValues = entry.CurrentValues.GetType().Name,
                    CurrentValues = entry.CurrentValues.GetType().Name,
                    Time = DateTime.Now.TimeOfDay
                };
                _context.Logs.Add(log);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CommentId"] = new SelectList(_context.Comments, "CommentId", "Notes", serviceRequest.CommentId);
            ViewData["Id"] = new SelectList(_context.Services, "ServiceId", "ServiceName", serviceRequest.Id);
            ViewData["TechnicianId"] = new SelectList(_context.AppUsers, "Id", "Id", serviceRequest.TechnicianId);
            return View(serviceRequest);
        }

        // GET: ServiceRequests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ServiceRequests == null)
            {
                return NotFound();
            }

            var serviceRequest = await _context.ServiceRequests.FindAsync(id);
            if (serviceRequest == null)
            {
                return NotFound();
            }
            ViewData["CommentId"] = new SelectList(_context.Comments, "CommentId", "Notes", serviceRequest.CommentId);
            ViewData["Id"] = new SelectList(_context.Services, "ServiceId", "ServiceName", serviceRequest.Id);
            ViewData["TechnicianId"] = new SelectList(_context.AppUsers, "Id", "Id", serviceRequest.TechnicianId);
            return View(serviceRequest);
        }

        // POST: ServiceRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,DateNeeded,Price,CommentId,TechnicianId,IsPending")] ServiceRequest serviceRequest)
        {
            if (id != serviceRequest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.ChangeTracker.DetectChanges();
                    _context.Update(serviceRequest);
                    LogsController.AddLog(_context, User.Identity.Name);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceRequestExists(serviceRequest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CommentId"] = new SelectList(_context.Comments, "CommentId", "Notes", serviceRequest.CommentId);
            ViewData["Id"] = new SelectList(_context.Services, "ServiceId", "ServiceName", serviceRequest.Id);
            ViewData["TechnicianId"] = new SelectList(_context.AppUsers, "Id", "Id", serviceRequest.TechnicianId);
            return View(serviceRequest);
        }

        // GET: ServiceRequests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ServiceRequests == null)
            {
                return NotFound();
            }

            var serviceRequest = await _context.ServiceRequests
                .Include(s => s.Comment)
                .Include(s => s.IdNavigation)
                .Include(s => s.Technician)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (serviceRequest == null)
            {
                return NotFound();
            }

            return View(serviceRequest);
        }

        // POST: ServiceRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ServiceRequests == null)
            {
                return Problem("Entity set 'HSMSContext.ServiceRequests'  is null.");
            }
            var serviceRequest = await _context.ServiceRequests.FindAsync(id);
            if (serviceRequest != null)
            {
                _context.ChangeTracker.DetectChanges();
                _context.ServiceRequests.Remove(serviceRequest);
                LogsController.AddLog(_context, User.Identity.Name);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceRequestExists(int id)
        {
            return _context.ServiceRequests.Any(e => e.Id == id);
        }
    }
}

ProjectWebApp/ProjectWebApp/Views/ServiceRequests/Create.cshtml
@model HSMSBusinessObjects.ServiceRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>ServiceRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNeeded" class="control-label"></label>
                <input asp-for="DateNeeded" class="form-control" />
                <span asp-validation-for="DateNeeded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CommentId" class="control-label"></label>
                <select asp-for="CommentId" class ="form-control" asp-items="ViewBag.CommentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TechnicianId" class="control-label"></label>
                <select asp-for="TechnicianId" class="form-control" asp-items="ViewBag.TechnicianId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

ProjectWebApp/ProjectWebApp/Views/ServiceRequests/Delete.cshtml
@model HSMSBusinessObjects.ServiceRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServiceRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateNeeded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateNeeded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNavigation.ServiceName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TechnicianId)
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

ProjectWebApp/ProjectWebApp/Views/ServiceRequests/Details.cshtml
@model HSMSBusinessObjects.ServiceRequest;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ServiceRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateNeeded)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateNeeded)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsPending)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsPending)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comment.CommentId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNavigation.ServiceName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Technician)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Technician.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

ProjectWebApp/ProjectWebApp/Views/ServiceRequests/Edit.cshtml
@model HSMSBusinessObjects.ServiceRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ServiceRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNeeded" class="control-label"></label>
                <input asp-for="DateNeeded" class="form-control" />
                <span asp-validation-for="DateNeeded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CommentId" class="control-label"></label>
                <select asp-for="CommentId" class="form-control" asp-items="ViewBag.CommentId"></select>
                <span asp-validation-for="CommentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TechnicianId" class="control-label"></label>
                <select asp-for="TechnicianId" class="form-control" asp-items="ViewBag.TechnicianId"></select>
                <span asp-validation-for="TechnicianId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

ProjectWebApp/ProjectWebApp/Views/ServiceRequests/Index.cshtml
@using ProjectWebApp.ViewModel;
@model NewServiceRequestViewModel;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Service Request List</h1>

<div class="col-md-6">
    <h2>Search</h2>
    <form asp-controller="ServiceRequests" asp-action="Index">
        Search Name:
        <input type="text" name="SearchString" asp-for="SearchString" placeholder="Enter service request" />
        <button type="submit" class="btn btn-outline-primary">Search</button>
        <a asp-controller="ServiceRequests" asp-action="Index" class="btn btn-outline-danger">
            Clear
        </a>
    </form>
</div>

<p>
    @if (User.IsInRole("Admin") || User.IsInRole("User"))
    {
        <br />
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.serviceRequest.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.serviceRequest.DateNeeded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.serviceRequest.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.serviceRequest.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.serviceRequest.IdNavigation.ServiceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.serviceRequest.TechnicianId)
            </th>
            @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Technician") || User.IsInRole("User"))
            {
                <th>Action</th>
            }
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ServiceRequests) 
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateNeeded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNavigation.ServiceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TechnicianId)
            </td>

            @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Technician") || User.IsInRole("User"))
            {
                <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                        </svg>
                        Edit
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-data" viewBox="0 0 16 16">
                            <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0z" />
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z" />
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z" />
                        </svg>
                        Details
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                        </svg>
                        Delete
                        </a>
                </td>
            }
        </tr>
    }
    </tbody>
</table>