ProjectWebApp/ProjectWebApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HSMSBusinessObjects;
using ProjectWebApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace ProjectWebApp.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly HSMSContext _context;

        public CategoriesController()
        {
            _context = new HSMSContext();
        }

        // GET: Categories
        public async Task<IActionResult> Index(string SearchString)
        {
            IEnumerable<Category> categoryList;

            categoryList = _context.Categories.Include(x => x.Manager);

            if (!string.IsNullOrEmpty(SearchString))
            {
                categoryList = categoryList.Where(x => x.CategoryName.Contains(SearchString));
            }

            var categoryVM = new NewCategoryViewModel
            {
                Categories = categoryList,
                Users = _context.AppUsers
            };

            return View(categoryVM);
        }

        // GET: Categories/Details/5
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.Manager)
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var viewModel = new NewCategoryViewModel
            {
                category = new Category(),
                Categories = _context.Categories,
                Users = _context.AppUsers
            };

            return View(viewModel);
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(NewCategoryViewModel newCat)
        {
            if(newCat == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.ChangeTracker.DetectChanges();
                _context.Categories.Add(newCat.category);

                var entry = _context.ChangeTracker.Entries().FirstOrDefault();

                Log log = new Log
                {
                    Table = entry.Entity.GetType().Name,
                    Status = entry.State.ToString(),
                    LDate = DateTime.Now,
                    UserId = _context.AppUsers.Where(x => x.UserName == User.Identity.Name).FirstOrDefault().Id,
                    User = _context.AppUsers.Where(x => x.Id == _context.AppUsers.Where(x => x.UserName == User.Identity.Name).FirstOrDefault().Id).FirstOrDefault(),
                    OriginalValues = entry.CurrentValues.GetType().Name,
                    CurrentValues = entry.CurrentValues.GetType().Name,
                    Time = DateTime.Now.TimeOfDay
                };
                _context.Logs.Add(log);

                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var viewModel = new NewCategoryViewModel
                {
                    category = newCat.category,
                    Categories = _context.Categories,
                    Users = _context.AppUsers
                };
                return View(viewModel);
            }
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            ViewData["ManagerId"] = new SelectList(_context.AppUsers, "Id", "Id", category.ManagerId);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName,Description,ManagerId")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.ChangeTracker.DetectChanges();
                    _context.Update(category);
                    LogsController.AddLog(_context, User.Identity.Name);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.AppUsers, "Id", "Id", category.ManagerId);
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.Manager)
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'HSMSContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            _context.ChangeTracker.DetectChanges();
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            LogsController.AddLog(_context, User.Identity.Name);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

ProjectWebApp/ProjectWebApp/Controllers/MonitoringController.cs
using HSMSBusinessObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectWebApp.ViewModel;

namespace ProjectWebApp.Controllers
{
    public class MonitoringController : Controller
    {
        private readonly HSMSContext _context;

        public MonitoringController()
        {
            _context = new HSMSContext();
        }

        [Authorize(Roles ="Admin,Manager")]
        public IActionResult Index(int? catId, string? SearchCategory)
        {
            string catName = _context.Categories.Where(x => x.CategoryId == catId).FirstOrDefault()?.CategoryName;

            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "CategoryName");

            if (!catId.HasValue)
            {
                return View(new RequestMonitoringViewModel());
            }

            var totalRequests = GetTotalRequestCount(catId);
            var pendingRequests = GetPendingRequestCount(catId);
            var overdueRequests = GetOverdueRequestCount(catId);

            var viewModel = new RequestMonitoringViewModel
            {
                TotalRequests = totalRequests,
                PendingRequests = pendingRequests,
                OverdueRequests = overdueRequests
            };

            return View(viewModel);
        }

        private int GetTotalRequestCount(int? catId)
        {
            return _context.ServiceRequests.Where(x => x.IdNavigation.CategoryId == catId).Count();
        }

        private int GetPendingRequestCount(int? catId)
        {
            return _context.ServiceRequests.Where(x => x.IdNavigation.CategoryId == catId && x.IsPending == true).Count();
        }

        private int GetOverdueRequestCount(int? catId)
        {
            DateTime today = DateTime.Today;
            return _context.ServiceRequests.Where(x => x.IdNavigation.CategoryId == catId && x.DateNeeded < today).Count();
        }
    }
}

ProjectWebApp/ProjectWebApp/Views/Categories/Create.cshtml
@using ProjectWebApp.ViewModel;
@model NewCategoryViewModel;
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="category.CategoryName" class="control-label"></label>
                <input asp-for="category.CategoryName" class="form-control" />
                <span asp-validation-for="category.CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="category.Description" class="control-label"></label>
                <input asp-for="category.Description" class="form-control" />
                <span asp-validation-for="category.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="category.ManagerId" class="control-label"></label>
                <select asp-for="category.ManagerId" class="form-control" asp-items="@Model.Users
                             .Select(i => new SelectListItem{ Text = i.UserName, Value = i.Id.ToString() })"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

ProjectWebApp/ProjectWebApp/Views/Categories/Delete.cshtml
@model HSMSBusinessObjects.Category;
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

ProjectWebApp/ProjectWebApp/Views/Categories/Details.cshtml
@model HSMSBusinessObjects.Category;
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CategoryId" class="btn btn-primary">Edit</a>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

ProjectWebApp/ProjectWebApp/Views/Categories/Edit.cshtml
@model HSMSBusinessObjects.Category;
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManagerId" class="control-label"></label>
                <select asp-for="ManagerId" class="form-control" asp-items="ViewBag.ManagerId"></select>
                <span asp-validation-for="ManagerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

ProjectWebApp/ProjectWebApp/Views/Categories/Index.cshtml
@using ProjectWebApp.ViewModel;
@model NewCategoryViewModel;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Category List</h1>

<div class="col-md-6">
    <h2>Search</h2>
    <form asp-controller="Categories" asp-action="Index">
        Search Name:
        <input type="text" name="SearchString" asp-for="SearchString" placeholder="Enter category name" />
        <button type="submit" class="btn btn-outline-primary">Search</button>
        <a asp-controller="Categories" asp-action="Index" class="btn btn-outline-danger">
            Clear
        </a>
    </form>
</div>

<p>
    @if (User.IsInRole("Admin"))
    {
        <br />
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.category.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category.Manager)
            </th>
            @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
            {
                <th>Action</th>
            }
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Categories)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manager.Id)
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.CategoryId" class="btn btn-primary mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                        </svg>
                        Edit
                    </a>
                }

                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Details" asp-route-id="@item.CategoryId" class="btn btn-secondary mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-data" viewBox="0 0 16 16">
                            <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0z" />
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z" />
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z" />
                        </svg>
                        Details
                    </a>
                }

                @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                {
                    <a href="@Url.Action("Index", "Monitoring", new { catId = item.CategoryId })" class="btn btn-info mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-display" viewBox="0 0 16 16">
                            <path d="M0 4s0-2 2-2h12s2 0 2 2v6s0 2-2 2h-4q0 1 .25 1.5H11a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1h.75Q6 13 6 12H2s-2 0-2-2zm1.398-.855a.76.76 0 0 0-.254.302A1.5 1.5 0 0 0 1 4.01V10c0 .325.078.502.145.602q.105.156.302.254a1.5 1.5 0 0 0 .538.143L2.01 11H14c.325 0 .502-.078.602-.145a.76.76 0 0 0 .254-.302 1.5 1.5 0 0 0 .143-.538L15 9.99V4c0-.325-.078-.502-.145-.602a.76.76 0 0 0-.302-.254A1.5 1.5 0 0 0 13.99 3H2c-.325 0-.502.078-.602.145" />
                        </svg>
                        Dashboard
                    </a>
                }

                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Delete" asp-route-id="@item.CategoryId" class="btn btn-danger mx-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                        </svg>
                        Delete
                    </a>
                }
            </td>
        </tr>
}
    </tbody>

</table>